### ISSUE TITLE
App closing on editing one particular task

### ISSUE THREAD

**Issue by rmkoske** [HabitRPG/habitrpg-android#390] opened 2016-01-26 01:08 UTC
I sent a crash log from the phone today with my username "rmkoske" in it. More detail for you: 

My user id: 32a8b0e5-398d-4d60-a695-aa84033608cd
I use a Samsung Galaxy S5 with Android version 5.1.1.
I was trying to edit the daily called "8,500 Steps".  It seems to reliably close the app every time I try to select it for editing.  (AKA, when I tap on the text field.)  I've repeated this behavior on this one task something like six times in a row now.  I didn't test every other task, but I have successfully entered editing mode for others since I noticed this behavior, so I'm assuming that it is only this one task.

I went into the website and edited the task successfully.  The edit (making it not active on any day) shows on the app, but the task still closes the app when I tap the text field.

I'm not mad about this, just trying to help the devs with extra data.  So feel free to close this immediately (though if this wasn't helpful feedback would be nice.  :smile: )  I'm also willing to try things and send more reports from the phone if that would be helpful.  I'm not terribly worried about my task.  I figure worst case I'll delete it and make a new one.

**Comment by Alys** [comment] 2016-01-26 01:25
The database entry for this task has the `startDate` set to `null`. No other Dailies in @rmkoske's account have a startDate of null (rmkoske, I didn't look at the text of your other tasks; I just searched for startDates and found no other nulls).

rmkoske, it would be interesting to know if this problem disappears if you edit the Daily on the website and give it a start date. Note that I'm not an Android dev, so this might be irrelevant.

**Comment by vIiRuS** [comment] 2016-01-26 01:38
@Alys has most likely found the cause. I'll try to get a fix for this in the next update.

**Comment by Alys** [comment] 2016-01-26 01:43
Let me know if you want me to set a null value in any test accounts.

**Comment by Alys** [comment] 2016-01-26 02:51
The API (v2) allows you to set the `startDate` for a Daily to `null`

**Comment by rmkoske** [comment] 2016-01-26 03:39
It does seern to be the null start date. 
I set a start date on it via the website, and the problem disappears. I fiddled with it some. Resetting it null makes the problem cone back, and making another daily null makes that one cause closes.

**Comment by vIiRuS** [comment] 2016-01-26 14:04
Turns out I had already fixed this one! See #356

**Closed** 2016-01-26 14:06 UTC
